name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: "this_is_an_secret_key"
      DB_NAME: "ttg"
      DB_USER: "inzam"
      DB_PASSWORD: "3304"
      DB_HOST: "127.0.0.1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,[::1]"
      DEBUG_MODE: False
      TIME_ZONE: "Asia/Calcutta"
      CACHE_KEY_PREFIX: "Halo"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.6

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test
